management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus", "refresh", "info", "env", "mappings", "beans"]

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
spring:
  config:
    import: "configserver:"  # Removed "optional:" to enforce fail-fast
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 2500 # 2.5s - reduced from 5s
      request-read-timeout: 2500 # 2.5s - reduced from 5s
      fail-fast: false  # Changed to true
      retry:
        max-attempts: 8  # Increased from 6
        initial-interval: 1500 # 1.5s - increased from 1s
        max-interval: 3000 # 3s - increased from 2s
        multiplier: 1.5  # Increased from 1.1 for more aggressive backoff    org.springframework.cloud.config: DEBUG
    org.springframework.security: INFO
  file:
    name: logs/patient-service.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB
  group:
    patient:
      - "com.pam.patientservice.controller"

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5